# Generated by Django 4.2.8 on 2024-01-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalOrderList",
            fields=[
                (
                    "ordernumber",
                    models.CharField(
                        db_column="OrderNumber",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "orderdate",
                    models.DateField(blank=True, db_column="OrderDate", null=True),
                ),
                (
                    "orderstatus",
                    models.CharField(
                        blank=True, db_column="OrderStatus", max_length=1, null=True
                    ),
                ),
                ("completed", models.BooleanField(db_column="Completed")),
                (
                    "soldtoname",
                    models.CharField(
                        blank=True, db_column="SoldToName", max_length=41, null=True
                    ),
                ),
                (
                    "totalamount",
                    models.DecimalField(
                        blank=True,
                        db_column="TotalAmount",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "workflowstatus",
                    models.CharField(
                        blank=True, db_column="WorkFlowStatus", max_length=80, null=True
                    ),
                ),
                (
                    "workflowstatusdate",
                    models.DateField(
                        blank=True, db_column="WorkFlowStatusDate", null=True
                    ),
                ),
                (
                    "qtybackordered",
                    models.DecimalField(
                        blank=True,
                        db_column="QtyBackordered",
                        decimal_places=7,
                        max_digits=38,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "_Portal_Order_List",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PortalProductFeed",
            fields=[
                (
                    "id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=38, null=True
                    ),
                ),
            ],
            options={
                "db_table": "_Portal_Product_Feed",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Portaltrailgearorders",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "ship_to",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=150
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=50
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=512,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "portaltrailgearorders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "guidproduct",
                    models.CharField(
                        db_column="tbOrderDetail - GUIDOrder__GUIDProduct",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qtyordered",
                    models.DecimalField(
                        blank=True,
                        db_column="QtyOrdered",
                        decimal_places=7,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "avgprice",
                    models.DecimalField(
                        blank=True,
                        db_column="AvgPrice",
                        decimal_places=7,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        blank=True,
                        db_column="Gross",
                        decimal_places=6,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "productid",
                    models.CharField(
                        blank=True,
                        db_column="tbProduct - GUIDProduct__ProductID",
                        max_length=159,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="tbProduct - GUIDProduct__Description",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "_Portal_Product_List",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WaitingdropshipTurn14",
            fields=[
                (
                    "ordernumber",
                    models.CharField(
                        db_column="OrderNumber",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "orderdate",
                    models.DateTimeField(blank=True, db_column="OrderDate", null=True),
                ),
                (
                    "orderstatus",
                    models.CharField(
                        blank=True, db_column="OrderStatus", max_length=1, null=True
                    ),
                ),
                (
                    "ponumber",
                    models.CharField(
                        blank=True, db_column="PONumber", max_length=40, null=True
                    ),
                ),
                (
                    "workflowstatus",
                    models.CharField(
                        blank=True, db_column="WorkFlowStatus", max_length=80, null=True
                    ),
                ),
            ],
            options={
                "db_table": "_WaitingDropship_Turn14",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ProductTest",
        ),
    ]
